### ISSUE TITLE
Subdir for app

### ISSUE THREAD

**Issue by pietercolpaert** [oSoc14/Artoria#1]
I would remove the subdir `BelfortApp`. Just put the project in the root folder. For code reviewers it's yet another dir to cd in and it's yet another click to see the contents on github ;-)

**Comment by coreation** [comment]
Apparently, according to @yungpanda it can't hurt to have this structure in Android apps.

**Comment by pietercolpaert** [comment]
@yungpanda Let's meet outside at 4pm, behind the shed.
