### ISSUE TITLE
Obtaining data

### ISSUE THREAD

**Issue by laurens-dg** [oSoc14/Artoria#12]
1) Get the data, sparql? data provided by artoria?
2) Download data, moment of last download will be saved in SharedPreferences. We'll download daily.

**Comment by coreation** [comment]
Make sure all of your work (code, github issue, descriptions, ...) is in english. And definitly not a mix-up ;) Can't you get the data once a day and store it locally on your phone?

**Comment by laurens-dg** [comment]
Whoops, slipped up. Issue was updated to english and with the latest decisions.
