### ISSUE TITLE
Investigate/implement  Google maps instead of Open Street Map

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#15]
Investigate the use of google maps instead of open street map in this application

**Comment by dieterbeelaert** [comment]
Limitations of the google directions api:

The Directions API has the following limits in place:

# Users of the free API:

2,500 directions requests per 24 hour period.
Up to 8 waypoints allowed in each request. Waypoints are not available for transit directions.
10 requests per second.

# Maps for Business customers:

100,000 directions requests per 24 hour period.
23 waypoints allowed in each request. Waypoints are not available for transit directions.
10 requests per second.

**Comment by dieterbeelaert** [comment]
# Mapquest API (currently used for the routing)

![image](https://cloud.githubusercontent.com/assets/6142860/3467026/c4860902-028a-11e4-9764-e4ac1a9dd235.png)

**Comment by coreation** [comment]
Alright, use OSM droid, if the directions API isn't unlimited then we wont use it. Make sure though you create the webview in which the map, directions etc. is implemented as such so you can swap it out easily with something else (e.g. google maps) who knows we might run into problems with droid OSM later on.

**Comment by ahluntang** [comment]
Google recommends using Intents for directions though, where it opens the Google Maps application (or another application the user can define as preferred/default navigation application). There are no limits in using Google Maps app for directions.

**Comment by coreation** [comment]
Actually this is a good idea, we don't need to create our own application
then, isn't there a limit on how many waypoints though?

On Thu, Jul 3, 2014 at 10:30 AM, Ah-Lun Tang notifications@github.com
wrote:

> Google recommends using Intents for directions though, where it opens the
> Google Maps application (or another application the user can define as
> preferred/default navigation application). There are no limits in using
> Google Maps app for directions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oSoc14/Artoria/issues/15#issuecomment-47880139.

## 

Met vriendelijke groeten,

Jan Vansteenlandt

**Comment by dieterbeelaert** [comment]
I think we'll stick to original plan. Starting Google Maps from an intent is cool, but I couldn't add more waypoints on the route ...
