### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#3]
Start page for app, 

The user needs to select his language, this needs to be stored in shared preferences.
So the user will see this view the first time he starts the app

**Comment by coreation** [comment]
Good, but I think dutch will be the default language, consider this as a low priority feature in the large scope of the project.

**Comment by laurens-dg** [comment]
This is pretty much done, Your language preferences are asked the first time the app is started.
But translations aren't as of yet provided
