### ISSUE TITLE
Mixare licensing

### ISSUE THREAD

**Issue by laurens-dg** [oSoc14/Artoria#36]
There's a copyright license when mixare is started, do we need to keep it? I know next to nothing about licensing.

Paging @pietercolpaert for an expert opinion.

**Comment by laurens-dg** [comment]
The license:
Copyright (C) 2010- Peer internet solutions
        \n\nThis program is free software:  you can redistribute it and/or modify it under the terms of the
        GNU General Public License as published by the Free Software Foundation, either version 3 of the License,
        or at your option) any later version.
        \n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
        the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
        License for more details.
        \n\n You should have received a copy of the GNU General Public License along with this program.
        If not, see &lt;http://www.gnu.org/licenses/&gt;

**Comment by pietercolpaert** [comment]
If that's Mixare's license, we need to use the same license, but now with a copyright notice added:
Copyright © 2014 Open Knowledge (Foundation) Belgium

**Comment by coreation** [comment]
I think the most important question is, do we need to keep the pop-up when mixare is started. I don't think we need to, a mentioning of the license in the README should be enough.

**Comment by laurens-dg** [comment]
I removed it, and will put it on github, with a reference to the original mixare project.
