### ISSUE TITLE
Shortest path route

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#39]
It would be cool if there is a function that will calculate the shortest path between the POI's on the route

**Comment by coreation** [comment]
You closed both issues, if you still want to solve this, this is an NP problem, several heuristic approaches and algorithms are aiming to solve a "shortest path" problem. Doesn't OSM support this?

**Comment by laurens-dg** [comment]
@coreation This issue is still open, I just closed the duplicate ;)

**Comment by dieterbeelaert** [comment]
Or to display the distance/time between the POI's in the route planning view.

**Comment by coreation** [comment]
Oh my bad, the "related issue closed" button is being deceiving ;).
