### ISSUE TITLE
Add a standard route?

### ISSUE THREAD

**Issue by laurens-dg** [oSoc14/Artoria#40]
Artoria could give a example route that could be accessed with a button on the main page.

**Comment by laurens-dg** [comment]
I'm sending a mail to ask for more information

**Comment by laurens-dg** [comment]
Even though I think it's a good idea, the client responded with;
Blijkbaar is een standaardroute al iets dat aangeboden wordt door Stad Gent. Voor ons is dat dus niet nodig, aangezien de meerwaarde ervan beperkt is.

So this issue is closed as wontfix

**Comment by coreation** [comment]
:+1: Now that's adding context to an issue ;)
