### ISSUE TITLE
Save the selected route

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#44]
The current route isn't saved, so when the user closes the app the route is lost .. Save it in the database or shared preferences? ...

**Comment by coreation** [comment]
Normally this should be stored in a database.

**Comment by laurens-dg** [comment]
Keeping performance and ease of programming in mind I might be leaning towards shared preferences.
Rationale; We only need to store a list of id's, this could be a string, seperated by whatever separator we feel like because the POI's are already saved to a database.
