### ISSUE TITLE
Building view

### ISSUE THREAD

**Issue by dieterbeelaert** [oSoc14/Artoria#5]
View + details of each building (see wireframe ...)

**Comment by coreation** [comment]
Mind you that this is an open source repository, visible for everybody ( -> where is that wireframe? ). As an outstander I should be able to at least somewhat understand what the issue is all about.

**Comment by laurens-dg** [comment]
Design: non existant.
Images aren't loading correctly.
But the view's there.

**Comment by laurens-dg** [comment]
Images not loading was due to incorrect app permissions. That's been fixed now.

**Comment by coreation** [comment]
Great! Even better would be now that you commit those changes specific to this issue and use the github referencing, that way your comments align with pushed commits. Just an FYI ;).
